apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-east-1
  version: "1.29"

vpc:
  cidr: "10.0.0.0/16"

managedNodeGroups:
  - name: eks-node-group
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    privateNetworking: true
    labels:
      environment: dev
      team: devops
