version: '3.9'

services:
  backend:
    container_name: medium-backend
    build: ./backend
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  frontend:
    container_name: medium-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8787/api
    command: ["npm", "run", "dev"]