services:
  backend:
    build: ./backend
    container_name: medium-backend
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: medium-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8787/api
