name: DevFlow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env files (for local dev ports)
        run: |
          echo "VITE_BACKEND_URL=http://localhost:8787/api" > frontend/.env
          echo "PORT=8787" > backend/.env

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          sleep 10  # wait for services to start

      - name: Check backend health
        run: curl --fail http://localhost:8787/api/posts || exit 1

      - name: Check frontend health
        run: curl --fail http://localhost:5173 || exit 1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Trivy scan backend
        run: |
          docker images
          trivy image --exit-code 1 --severity HIGH,CRITICAL medium-backend || exit 0

      - name: Trivy scan frontend
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL medium-frontend || exit 0

      - name: Shutdown containers
        if: always()
        run: docker-compose down

      - name: Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*DevFlow CI Notification*\nRepo: `${{ github.repository }}`\nBranch: `${{ github.ref_name }}`\nStatus: *${{ job.status }}*\n👉 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
