name: DevFlow CI

on:
  push:
    branches: [main, 'hotfix/**']
  pull_request:
    branches: [main]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env files (if needed)
        run: |
          echo "VITE_BACKEND_URL=http://backend:8787/api" > frontend/.env
          echo "PORT=8787" > backend/.env

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          sleep 15

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend
          format: table
          ignore-unfixed: true
          exit-code: 1

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend
          format: table
          ignore-unfixed: true
          exit-code: 1

      - name: Shut down containers
        run: docker-compose down

      - name: Notify Slack - Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ *DevFlow CI* passed (Trivy scan clean) on `${{ github.ref_name }}` by `${{ github.actor }}`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ *DevFlow CI* failed (Trivy or build error) on `${{ github.ref_name }}` by `${{ github.actor }}`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
