# name: Deploy to Dev Environment

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   deploy-dev:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up kubectl
#         uses: azure/setup-kubectl@v3
#         with:
#           version: 'v1.29.0'

#       - name: Set up Helm
#         uses: azure/setup-helm@v3

#       - name: Deploy to Dev with Helm
#         run: |
#           helm upgrade --install devflow-dev ./helm/ \
#             --namespace dev \
#             --values helm/values-dev.yaml
